language: go
sudo: false
go:
  - 1.9.x

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev

install:
  - make deps

go_import_path: github.com/evilsocket/bettercap-ng

script:
  - make test

